-- Database: Database-001
use [Database-001]
go
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6001', 'React Native');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6001', 'Xcode');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6001', 'Firebase');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6002', 'React');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6002', 'Node.js');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6002', 'MongoDB');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6003', 'Angular');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6003', 'Node.js');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6003', 'PostgreSQL');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6004', 'PHP');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6004', 'MySQL');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6005', 'Android Studio');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6005', 'Firebase');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6006', 'React');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6006', 'Node.js');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6006', 'MongoDB');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6007', 'Vue.js');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6007', 'Firebase');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6008', 'Flutter');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6008', 'Firebase');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6009', 'HTML');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6009', 'CSS');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6009', 'JavaScript');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6010', 'Figma');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6010', 'Sketch');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6011', 'React');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6011', 'Node.js');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6011', 'MongoDB');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6012', 'Vue.js');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6012', 'Node.js');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6012', 'MySQL');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6013', 'React Native');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6013', 'AWS');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6014', 'Flutter');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6014', 'Firebase');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6015', 'Unity');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6015', 'C#');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6016', 'React');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6016', 'Node.js');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6016', 'MongoDB');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6017', 'Angular');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6017', 'TypeScript');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6018', 'React');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6018', 'Node.js');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6018', 'MySQL');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6019', 'React Native');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6019', 'Firebase');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6020', 'Python');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6020', 'BeautifulSoup');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6021', 'Flutter');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6021', 'SQLite');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6022', 'React Native');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6022', 'Firebase');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6023', 'React');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6023', 'Node.js');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6023', 'MongoDB');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6024', 'React Native');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6024', 'MySQL');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6025', 'React Native');
INSERT INTO SoftwareDevelopmentTool (SoftwareServiceID, DevelopmentTool) VALUES ('6025', 'Node.js');