INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('1', 'Laptop', '10', '1200', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('2', 'Smartphone', '20', '800', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('3', 'Monitor', '15', '300', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('4', 'Keyboard', '50', '20', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('5', 'Mouse', '60', '15', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('6', 'Printer', '12', '150', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('7', 'Router', '25', '75', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('8', 'External Hard Drive', '18', '90', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('9', 'Tablet', '30', '250', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('10', 'Headphones', '40', '50', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('11', 'Webcam', '35', '45', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('12', 'Smartwatch', '22', '200', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('13', 'Graphic Tablet', '8', '350', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('14', 'Speaker', '28', '70', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('15', 'Power Bank', '55', '25', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('16', 'USB Flash Drive', '100', '10', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('17', 'Desk Chair', '10', '120', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('18', 'Office Desk', '7', '300', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('19', 'Gaming Chair', '5', '250', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('20', 'Projector', '6', '400', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('21', 'Camera', '12', '550', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('22', 'Tripod', '20', '60', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('23', 'Whiteboard', '15', '75', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('24', 'Smart TV', '8', '700', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('25', 'Air Conditioner', '5', '1000', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('26', 'Microwave', '10', '180', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('27', 'Washing Machine', '3', '800', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('28', 'Refrigerator', '4', '1500', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('29', 'Dishwasher', '3', '900', '1');
INSERT INTO Item (ItemID, ItemName, Quantity, Price, CompanyID) VALUES ('30', 'Electric Kettle', '50', '35', '1');