INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('1', 'JavaScript');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('1', 'TypeScript');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('1', 'Node.js');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('2', 'Data Analysis');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('2', 'SQL');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('2', 'Excel');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('3', 'Cloud Computing');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('3', 'Networking');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('3', 'Python');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('4', 'CICD');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('4', 'Docker');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('4', 'Kubernetes');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('5', 'Agile Methodologies');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('5', 'Project Management');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('5', 'Leadership');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('6', 'Penetration Testing');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('6', 'Security Audits');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('6', 'Networking');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('7', 'SQL Server');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('7', 'Database Design');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('7', 'Performance Tuning');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('8', 'React.js');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('8', 'JavaScript');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('8', 'HTML/CSS');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('9', 'Routing and Switching');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('9', 'Network Security');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('9', 'Firewall Configuration');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('10', 'Automation Testing');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('10', 'Java');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('10', 'JUnit');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('11', 'Node.js');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('11', 'JavaScript');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('11', 'Backend Development');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('12', 'Flutter');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('12', 'Dart');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('12', 'Mobile Development');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('13', 'Unity');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('13', 'C#');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('13', 'Game Development');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('14', 'Machine Learning');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('14', 'Python');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('14', 'Deep Learning');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('15', 'System Troubleshooting');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('15', 'Networking');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('15', 'Technical Support');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('16', 'User Research');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('16', 'UX Design');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('16', 'Wireframing');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('17', 'AWS');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('17', 'Cloud Computing');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('17', 'DevOps');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('18', 'Python');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('18', 'Machine Learning');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('18', 'Data Science');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('19', 'MERN Stack');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('19', 'JavaScript');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('19', 'React.js');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('19', 'Node.js');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('20', 'IT Strategy');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('20', 'Consulting');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('20', 'Cloud Architecture');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('21', 'Firewall Management');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('21', 'Security');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('21', 'Network Protection');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('22', 'System Design');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('22', 'Architecture');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('22', 'Database Design');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('23', 'Ansible');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('23', 'Automation');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('23', 'DevOps');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('24', 'NoSQL Databases');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('24', 'MongoDB');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('24', 'Database Architecture');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('25', 'Cisco Networking');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('25', 'Network Design');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('25', 'Router Configuration');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('26', 'Figma');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('26', 'UI Design');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('26', 'Prototyping');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('27', 'Django');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('27', 'Python');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('27', 'Web Development');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('28', 'Documentation');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('28', 'Technical Writing');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('28', 'API Documentation');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('29', 'Ethereum');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('29', 'Blockchain');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('29', 'Smart Contracts');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('30', 'HTML/CSS');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('30', 'JavaScript');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('30', 'Web Development');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('31', 'Kotlin');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('31', 'Android Development');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('31', 'Mobile Apps');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('32', 'Manual Testing');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('32', 'QA Testing');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('32', 'Automation Tools');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('33', 'Data Mining');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('33', 'Data Analysis');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('33', 'Machine Learning');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('34', 'Penetration Testing');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('34', 'Network Security');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('34', 'Ethical Hacking');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('35', 'Automation Testing');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('35', 'Test Automation');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('35', 'Selenium');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('36', 'Agile Methodologies');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('36', 'Project Management');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('36', 'Scrum');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('37', 'Unity');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('37', 'Game Design');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('37', 'VR Development');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('38', 'System Troubleshooting');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('38', 'Technical Support');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('38', 'Windows Administration');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('39', 'NoSQL Databases');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('39', 'MongoDB');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('39', 'Cassandra');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('40', 'Google Cloud Platform');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('40', 'Cloud Computing');
INSERT INTO EmployeeSkill (EmployeeID, Skill) VALUES ('40', 'DevOps');