-- Database: Database-001
use [Database-001]
go
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8001', 'Norton Antivirus', '2023');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8002', 'Windows 10', 'Windows 10 Pro');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8003', 'McAfee Antivirus', '2022');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8004', 'AVG Antivirus', '2023');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8005', 'Photoshop', 'Photoshop 2022');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8006', 'Slack', '2023.04');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8007', 'Bitdefender Antivirus', '2022');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8008', 'NVIDIA Driver', '472.12');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8009', 'Zoom', 'Zoom 5.11');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8010', 'Microsoft Office', 'Office 2021');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8011', 'AutoCAD', 'AutoCAD 2023');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8012', 'Windows Defender', '2023');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8013', 'League of Legends', '2023.01');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8014', 'macOS', 'macOS 13');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8015', 'Recuva', 'Recuva 2023');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8016', 'Outlook', 'Outlook 2023');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8017', 'Ubuntu', 'Ubuntu 20.04');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8018', 'SQL Server', 'SQL Server 2022');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8019', 'Python', 'Python 3.10');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8020', 'Google Chrome', 'Chrome 94.0');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8021', 'Firefox', 'Firefox 93');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8022', 'Bitdefender Total Security', '2023');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8023', 'Microsoft Office 365', '365.23');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8024', 'Spybot Search & Destroy', 'Spybot 2023');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8025', 'CorelDRAW', 'CorelDRAW 2023');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8026', 'Evernote', 'Evernote 10.2');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8027', 'Adobe Premiere Pro', 'Premiere Pro 2023');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8028', 'VMware Workstation', 'VMware Workstation 16');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8029', 'Wireshark', 'Wireshark 4.0');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('8030', 'Spotify', 'Spotify 2023.08');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('4003', 'Windows Software', 'Add Specific Version');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('4008', 'Smartphone Software Update', 'Add Specific Version');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('4009', 'Optimize Dell Utility Software', 'Latest Revi TCUX Best!');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('4013', 'Add Software Details', 'Add Specific Version');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('4020', 'Resolve Smartphone Sync Error', 'Check with Team');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('4021', 'Google Drive Error Issue', 'Update After Team');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('4023', 'Antivirus Full Repair', 'Perform Required Action');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('4027', 'Windows Software Issues', 'Pending Updates');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('4028', 'Specific Software Issue', 'Track Customer');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('4030', 'Verify on Meeting Issue', 'Update Specific Details');
INSERT INTO SoftwareRepairService (SoftwareRepairServiceID, SoftwareType, SoftwareVersion) VALUES ('4032', 'Laptop BIOS Issue', 'Latest Version Fix');