-- Database: Database-001
use [Database-001]
go
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7001', 'Hard Drive', '2019');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7002', 'Keyboard', '2020');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7003', 'Graphics Card', '2021');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7004', 'Power Supply', '2018');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7005', 'Laptop Screen', '2022');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7006', 'Processor', '2021');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7007', 'Hard Drive', '2020');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7008', 'RAM', '2022');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7009', 'Graphics Card', '2021');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7010', 'CPU Fan', '2020');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7011', 'Hard Drive', '2018');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7012', 'SSD', '2022');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7013', 'Monitor', '2020');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7014', 'Laptop Motherboard', '2019');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7015', 'Hard Drive', '2020');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7016', 'Power Supply', '2021');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7017', 'CPU', '2022');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7018', 'Graphics Card', '2021');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7019', 'Keyboard', '2022');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7020', 'Monitor', '2020');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7021', 'SSD', '2019');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7022', 'Laptop Battery', '2021');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7023', 'Hard Drive', '2022');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7024', 'SSD', '2019');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7025', 'Laptop Motherboard', '2020');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7026', 'Graphics Card', '2021');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7027', 'CPU Cooling Fan', '2022');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7028', 'SSD', '2020');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7029', 'Laptop Display', '2022');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('7030', 'Hard Drive', '2020');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4001', 'Phone Screen', '2021');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4002', 'Laptop Hard Drive', '2022');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4004', 'Phone Battery', '2020');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4005', 'PC RAM', '2021');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4006', 'Tablet Screen', '2022');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4007', 'MacBook Key', '2021');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4010', 'Laptop Battery', '2022');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4011', 'Smartwatch Screen', '2021');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4012', 'Phone Speaker', '2020');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4014', 'Laptop Screen', '2022');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4015', 'Tablet Battery', '2021');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4016', 'Phone Camera', '2020');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4017', 'PC Hard Drive', '2022');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4018', 'Smartphone Screen', '2021');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4019', 'Laptop Upgrade', '2020');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4022', 'Phone Charger', '2021');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4024', 'PC Power Supply', '2020');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4025', 'Smartphone Hardware', '2021');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4026', 'Laptop Keyboard', '2022');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4029', 'Tablet Speaker', '2021');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4031', 'Laptop Graphic Card', '2020');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4033', 'Phone Back Cover', '2021');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4034', 'Tablet Camera', '2022');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4035', 'PC RAM', '2020');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4036', 'Smartphone Charging Port', '2022');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4037', 'Laptop Audio Jack', '2021');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4038', 'Tablet Repair', '2020');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4039', 'Phone Water Damage', '2021');
INSERT INTO HardwareRepairService (HardwareRepairServiceID, Component, ProductionYear) VALUES ('4040', 'PC Overheating', '2020');